// AUTHENTICATION ACTION TYPES
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// ABOUT ACTION TYPES
export const SHOW_ROUTER_INFO = "SHOW_ROUTER_INFO";
export const SHOW_REDUX_INFO = "SHOW_REDUX_INFO";
export const SHOW_THUNK_INFO = "SHOW_THUNK_INFO";
export const SHOW_SCSS_INFO = "SHOW_SCSS_INFO";
export const SHOW_NAVIGATION_INFO = "SHOW_NAVIGATION_INFO";
export const SHOW_AUTH_INFO = "SHOW_AUTH_INFO";
export const SHOW_LAYOUT_INFO = "SHOW_LAYOUT_INFO";

// HOME ACTION TYPES
export const SET_HOME_DATA = "SET_HOME_DATA";
export const FETCH_HOME_DATA_FAILED = "FETCH_HOME_DATA_FAILED";
export const SELECT_BOOK = "SELECT_BOOK";
export const DESELECT_BOOK = "DESELECT_BOOK";

// DOM ACTION TYPES
export const ADD_TO_CART = "ADD_TO_CART";
export const SHOW_CART = "SHOW_CART";
export const HIDE_CART = "HIDE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SUB_ITEM_NUMBER = "SUB_ITEM_NUMBER";
export const ADD_ITEM_NUMBER = "ADD_ITEM_NUMBER";
export const CANCEL_ORDER_CONFIRMATION = "CANCEL_ORDER_CONFIRMATION";
export const CONFIRM_ORDER_CONFIRMATION = "CONFIRM_ORDER_CONFIRMATION";

export const TOGGLE_ON_ORDER_NOT_LOGGEDIN = "TOGGLE_ON_ORDER_NOT_LOGGEDIN";

export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";


// USER ACTION TYPES
export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";
export const SET_USER_ORDERS = "SET_USER_ORDERS";